allowBuilds:
  '@clerk/shared': true
  '@firebase/util': true
  '@google/genai': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  crfsuite: set this to true or false
  es5-ext: true
  esbuild: true
  fasttext: set this to true or false
  protobufjs: true
  re2: true
  sharp: true
